---
name: Main workflow

"on":
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 5.0.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          dune-cache: true

      - run: opam install . --deps-only --with-test --locked

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest --instrument-with bisect_ppx --force

      - run: opam exec -- bisect-ppx-report summary --per-file
