---
name: Main workflow

on:
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.13.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          dune-cache: true

      - run: opam install . --deps-only --with-doc --with-test --locked

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest --instrument-with bisect_ppx --force

      - run: opam exec -- bisect-ppx-report summary --per-file

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.ocaml-version }}-fex.exe
          path: _build/default/bin/fex.exe
