---
name: Main workflow

on:
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.13.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cached Infra
        uses: actions/cache@v2
        with:
          path: |
           ~/.opam
           _build
           C:\cygwin
           D:\a\fex\fex
          key: v${{ matrix.os }}-${{ matrix.ocaml-version }}-${{ hashFiles('**/*.opam*') }}
          restore-keys: |
            v{{ matrix.os }}-${{ matrix.ocaml-version }}-
            v{{ matrix.os }}-

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add fex.dev . --no-action

      - run: opam depext fex --yes --with-doc --with-test

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest --instrument-with bisect_ppx --force

      - run: opam exec -- bisect-ppx-report summary --per-file

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.ocaml-version }}-fex.exe
          path: _build/default/bin/fex.exe
